export const options = [
	{
		title: "Items",
		description: "Create standalone items and services that you buy and sell",
		linkTitle: "New Item",
		href: "/dashboard/inventory/items/new",
		enabled: true,
		img: "/items.svg",
	},
	{
		title: "Unit",
		description: "Define different units of measurement for your items",
		linkTitle: "New Unit",
		href: "/dashboard/inventory/unit/new",
		enabled: true,
		img: "/units.svg",
	},
	{
		title: "Supplier",
		description: "Define different units of measurement for your items",
		linkTitle: "New Supplier",
		href: "/dashboard/inventory/supplier/new",
		enabled: true,
		img: "/supply.svg",
	},
	{
		title: "Category",
		description: "Bundle different items together and sell them as kits",
		linkTitle: "New Category",
		href: "/dashboard/inventory/category/new",
		enabled: true,
		img: "/category.svg",
	},
	{
		title: "Brand",
		description: "Manage Brand associated with your items",
		linkTitle: "New Brand",
		href: "/dashboard/inventory/brand/new",
		enabled: true,
		img: "/brand.svg",
	},
	{
		title: "Warehouse",
		description: "Manage warehouses for your inventory",
		linkTitle: "New Warehouse",
		href: "/dashboard/inventory/warehouse/new",
		enabled: true,
		img: "/warehouse.svg",
	},
	{
		title: "Inventory Adjustments",
		description: "Transfer stock from the main warehouse",
		linkTitle: "New Adjustment",
		href: "/dashboard/inventory/adjustments/new",
		enabled: true,
		img: "/adjustments.svg",
	},
];
