export const optionsData = [
	{
		title: "Items",
		description: "Create standalone items and services that you buy and sell",
		linkTitle: "New Item",
		href: "/dashboard/inventory/items/new",
		enabled: true,
		img: "/tshirt.svg",
	},
	{
		title: "Units",
		description: "Define different units of measurement for your items",
		linkTitle: "New Unit",
		href: "/dashboard/inventory/units/new",
		enabled: true,
		img: "/group.svg",
	},
	{
		title: "Categories",
		description: "Bundle different items together and sell them as kits",
		linkTitle: "New Category",
		href: "/dashboard/inventory/categories/new",
		enabled: true,
		img: "/wardrobe.svg",
	},
	{
		title: "Brands",
		description: "Manage brands associated with your items",
		linkTitle: "New Brand",
		href: "/dashboard/inventory/brands/new",
		enabled: true,
		img: "/list.svg",
	},
	{
		title: "Warehouse",
		description: "Manage warehouses for your inventory",
		linkTitle: "New Warehouse",
		href: "/dashboard/inventory/warehouse/new",
		enabled: true,
		img: "/list.svg",
	},
];
